"""initial schema

Revision ID: 06e94e42b821
Revises: 
Create Date: 2025-11-23 21:43:52.516881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e94e42b821'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('team_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pull_requests',
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.Column('pull_request_name', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MERGED', name='pr_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pull_request_id')
    )
    op.create_table('team_members',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_name'], ['teams.team_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_name', 'user_id'),
    sa.UniqueConstraint('team_name', 'user_id', name='uq_team_member')
    )
    op.create_table('pr_reviewers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.pull_request_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'reviewer_id', name='uq_pr_reviewer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_reviewers')
    op.drop_table('team_members')
    op.drop_table('pull_requests')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
